services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/user_auth
    ports:
      - "3000:3000"

volumes:
  pgdata:
